[package]
name = "libmem"
version = "0.1.0"
edition = "2024"



[dependencies]
liblock = { path="../liblock/", version = "0.1.0" }


#[target.'cfg(not(test))'.dependencies]
#librand = { path="../librand", version = "0.1.0" }

#[target.'cfg(test)'.dependencies]
librand = { path="../librand", version = "0.1.0", features=["testing"] }
