[package]
name = "libequinox"
version = "0.1.0"
edition = "2024"
description = "unified library for both the Rhea kernel and the Equinox bootloader"

[dependencies]
#uefi = { version = "0.38.0", optional = true }
ministd = { path="../../../ministd", version="0.1.0", optional=true }


[features]
bootloader=[]
kernel=[]

#   exposes all APIs and creates unit test entries through the ministd library
testing=["dep:ministd", "ministd/testing"]

default=["bootloader"]
