[package]
name = "libtest"
description = "Registers tests for the harness to run"
version = "0.1.0"
edition = "2024"

[features]
testing=["macros/testing", "dep:inventory"]
harness=[]

default=[]

[dependencies]
inventory = { version="0.3.24", optional=true }
macros = { path="src/macros", version="0.1.0" }
